spark:
  app_name: "TemperatureStreamProcessor"
  packages: "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,com.datastax.spark:spark-cassandra-connector_2.12:3.5.0"
logging:
  level: "INFO"
  file: "logs/app.log"